// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eMotoCare.Infrastructure.Persistence;

#nullable disable

namespace eMotoCare.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EMotoCareDbContext))]
    partial class EMotoCareDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eMotoCare.Core.Entites.Account", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_name");

                    b.HasKey("AccountId")
                        .HasName("pk_accounts");

                    b.ToTable("accounts");
                });

            modelBuilder.Entity("eMotoCare.Core.Entites.AccountRole", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("account_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("LastEditBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("last_edit_by");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("AccountId", "RoleId")
                        .HasName("pk_account_roles");

                    b.ToTable("account_roles");
                });

            modelBuilder.Entity("eMotoCare.Core.Entites.Action", b =>
                {
                    b.Property<Guid>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("action_id");

                    b.Property<string>("ActionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("action_code");

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("action_name");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("ActionId")
                        .HasName("pk_actions");

                    b.ToTable("actions", (string)null);
                });

            modelBuilder.Entity("eMotoCare.Core.Entites.Address", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("address_id");

                    b.HasKey("AddressId")
                        .HasName("pk_addresses");

                    b.ToTable("addresses");
                });

            modelBuilder.Entity("eMotoCare.Core.Entites.Appointment", b =>
                {
                    b.Property<Guid>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("appointment_id");

                    b.Property<string>("AppointmentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("appointment_code");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("appointment_date");

                    b.Property<int>("AppointmentStatus")
                        .HasColumnType("int")
                        .HasColumnName("appointment_status");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("ProfileCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("profile_code");

                    b.Property<string>("ServiceCenterCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("service_center_code");

                    b.Property<string>("SlotTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("slot_time");

                    b.Property<string>("StaffCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("staff_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("VehicleCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vehicle_code");

                    b.Property<Guid>("VehicleStageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("vehicle_stage_id");

                    b.HasKey("AppointmentId")
                        .HasName("pk_appointments");

                    b.ToTable("appointments");
                });

            modelBuilder.Entity("eMotoCare.Core.Entites.EVCheck", b =>
                {
                    b.Property<Guid>("EVCheckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ev_check_id");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("appointment_id");

                    b.Property<DateTime>("CheckDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("check_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("EVCheckCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ev_check_code");

                    b.Property<Guid?>("ExecutedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("executed_by");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("EVCheckId")
                        .HasName("pk_ev_checks");

                    b.ToTable("ev_checks");
                });

            modelBuilder.Entity("eMotoCare.Core.Entites.EVCheckDetail", b =>
                {
                    b.Property<Guid>("EVCheckDetaikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ev_check_detaik_id");

                    b.Property<int>("ActionType")
                        .HasColumnType("int")
                        .HasColumnName("action_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EVCheckId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ev_check_id");

                    b.Property<string>("IamgeResult")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("iamge_result");

                    b.Property<Guid?>("PartItemReplacement")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("part_item_replacement");

                    b.Property<decimal?>("PartPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("part_price");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("result");

                    b.Property<Guid?>("ServicePriceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("service_price_id");

                    b.Property<int>("Solution")
                        .HasColumnType("int")
                        .HasColumnName("solution");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_price");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VehiclePartItem")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("vehicle_part_item");

                    b.HasKey("EVCheckDetaikId")
                        .HasName("pk_ev_check_details");

                    b.ToTable("ev_check_details");
                });

            modelBuilder.Entity("eMotoCare.Core.Entites.ExportNote", b =>
                {
                    b.Property<Guid>("ExportNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("export_note_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("ExportDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("export_date");

                    b.Property<Guid?>("ExportFrom")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("export_from");

                    b.Property<string>("ExportNoteCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("export_note_code");

                    b.Property<Guid?>("ExportTo")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("export_to");

                    b.Property<int>("ExportType")
                        .HasColumnType("int")
                        .HasColumnName("export_type");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<int>("TotalQuantityPart")
                        .HasColumnType("int")
                        .HasColumnName("total_quantity_part");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("ExportNoteId")
                        .HasName("pk_export_notes");

                    b.ToTable("export_notes");
                });

            modelBuilder.Entity("eMotoCare.Core.Entites.ExportNoteDetail", b =>
                {
                    b.Property<Guid>("ExpotNoteDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("expot_note_detail_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ExportNoteId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("export_note_id");

                    b.Property<Guid>("PartItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("part_item_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("ExpotNoteDetailId")
                        .HasName("pk_export_note_details");

                    b.ToTable("export_note_details");
                });

            modelBuilder.Entity("eMotoCare.Core.Entites.ImportNote", b =>
                {
                    b.Property<Guid>("ImportNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("import_note_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("import_date");

                    b.Property<Guid?>("ImportFrom")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("import_from");

                    b.Property<string>("ImportNoteCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("import_note_code");

                    b.Property<int>("ImportNoteStatus")
                        .HasColumnType("int")
                        .HasColumnName("import_note_status");

                    b.Property<Guid?>("ImportTo")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("import_to");

                    b.Property<int>("ImportType")
                        .HasColumnType("int")
                        .HasColumnName("import_type");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<int>("TotalPart")
                        .HasColumnType("int")
                        .HasColumnName("total_part");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("ImportNoteId")
                        .HasName("pk_import_notes");

                    b.ToTable("import_notes");
                });

            modelBuilder.Entity("eMotoCare.Core.Entites.ImportNoteDetail", b =>
                {
                    b.Property<Guid>("ImportNoteDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("import_note_detail_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ImportNoteId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("import_note_id");

                    b.Property<Guid>("PartItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("part_item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("ImportNoteDetailId")
                        .HasName("pk_import_note_details");

                    b.ToTable("import_note_details");
                });

            modelBuilder.Entity("eMotoCare.Core.Entites.Inventory", b =>
                {
                    b.Property<Guid>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("inventory_id");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("address_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("InventoryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("inventory_code");

                    b.Property<Guid>("InventoryManager")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("inventory_manager");

                    b.Property<Guid>("ServiceCenterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("service_center_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("InventoryId")
                        .HasName("pk_inventories");

                    b.ToTable("inventories");
                });

            modelBuilder.Entity("eMotoCare.Core.Entites.MaintenancePlan", b =>
                {
                    b.Property<Guid>("MaintenancePlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("maintenance_plan_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("MaintenancePlanCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("maintenance_plan_code");

                    b.Property<string>("MaintenancePlanname")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("maintenance_planname");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("TotalStage")
                        .HasColumnType("int")
                        .HasColumnName("total_stage");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("MaintenancePlanId")
                        .HasName("pk_maintenance_plans");

                    b.ToTable("maintenance_plans");
                });

            modelBuilder.Entity("eMotoCare.Core.Entites.MaintenanceStage", b =>
                {
                    b.Property<Guid>("MaintenanceStageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("maintenance_stage_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("MaintenanceInterval")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("maintenance_interval");

                    b.Property<Guid>("MaintenancePlanId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("maintenance_plan_id");

                    b.Property<string>("MaintenanceStageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("maintenance_stage_code");

                    b.Property<string>("MaintenanceStageName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("maintenance_stage_name");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("TimeMaintenance")
                        .HasColumnType("int")
                        .HasColumnName("time_maintenance");

                    b.Property<int>("Unit")
                        .HasColumnType("int")
                        .HasColumnName("unit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("MaintenanceStageId")
                        .HasName("pk_maintenance_stages");

                    b.ToTable("maintenance_stages");
                });

            modelBuilder.Entity("eMotoCare.Core.Entites.MaintenanceStageDetail", b =>
                {
                    b.Property<Guid>("MaintenanceStageDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("maintenance_stage_detail_id");

                    b.Property<int>("ActionType")
                        .HasColumnType("int")
                        .HasColumnName("action_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MaintenanceStageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("maintenance_stage_id");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("part_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("MaintenanceStageDetailId")
                        .HasName("pk_maintenance_stage_details");

                    b.ToTable("maintenance_stage_details");
                });

            modelBuilder.Entity("eMotoCare.Core.Entites.Module", b =>
                {
                    b.Property<Guid>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("module_id");

                    b.Property<string>("ModuleCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("module_code");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("module_name");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("ModuleId")
                        .HasName("pk_modules");

                    b.ToTable("modules");
                });

            modelBuilder.Entity("eMotoCare.Core.Entites.Page", b =>
                {
                    b.Property<Guid>("PageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("page_id");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsMenu")
                        .HasColumnType("bit")
                        .HasColumnName("is_menu");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("module_id");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.Property<string>("PageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("page_code");

                    b.Property<string>("PageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("page_url");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("PageId")
                        .HasName("pk_pages");

                    b.ToTable("pages");
                });

            modelBuilder.Entity("eMotoCare.Core.Entites.Part", b =>
                {
                    b.Property<Guid>("PartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("part_id");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cost_price");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsWarranty")
                        .HasColumnType("bit")
                        .HasColumnName("is_warranty");

                    b.Property<string>("PartCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("part_code");

                    b.Property<string>("PartName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("part_name");

                    b.Property<Guid>("PartTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("part_type_id");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("UnitWarrnty")
                        .HasColumnType("int")
                        .HasColumnName("unit_warrnty");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("WarrantyPeriod")
                        .HasColumnType("int")
                        .HasColumnName("warranty_period");

                    b.HasKey("PartId")
                        .HasName("pk_parts");

                    b.ToTable("parts");
                });

            modelBuilder.Entity("eMotoCare.Core.Entites.PartItem", b =>
                {
                    b.Property<Guid>("PartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("part_item_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InvetoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("invetory_id");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("part_id");

                    b.Property<int>("PartItemStatus")
                        .HasColumnType("int")
                        .HasColumnName("part_item_status");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("serial_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("PartItemId")
                        .HasName("pk_part_items");

                    b.ToTable("part_items");
                });

            modelBuilder.Entity("eMotoCare.Core.Entites.PartModel", b =>
                {
                    b.Property<Guid>("PartModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("part_model_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsWarranty")
                        .HasColumnType("bit")
                        .HasColumnName("is_warranty");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("part_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("UnitWarrnty")
                        .HasColumnType("int")
                        .HasColumnName("unit_warrnty");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VehicleModelId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("vehicle_model_id");

                    b.HasKey("PartModelId")
                        .HasName("pk_part_models");

                    b.ToTable("part_models");
                });

            modelBuilder.Entity("eMotoCare.Core.Entites.PartType", b =>
                {
                    b.Property<Guid>("PartTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("part_type_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("PartTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("part_type_code");

                    b.Property<string>("PartTypeName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("part_type_name");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("PartTypeId")
                        .HasName("pk_part_types");

                    b.ToTable("part_types");
                });

            modelBuilder.Entity("eMotoCare.Core.Entites.Payment", b =>
                {
                    b.Property<Guid>("PayemntId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("payemnt_id");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("appointment_id");

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("attachment_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("currency");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<decimal?>("PaidAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("paid_amount");

                    b.Property<string>("PaymentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payment_code");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int")
                        .HasColumnName("payment_method");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int")
                        .HasColumnName("payment_status");

                    b.Property<DateTime>("PaymentTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("payment_time");

                    b.Property<decimal?>("RemainingAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("remaining_amount");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<decimal?>("TotalPaidAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_paid_amount");

                    b.Property<string>("TransactionReference")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("transaction_reference");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("PayemntId")
                        .HasName("pk_payments");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("eMotoCare.Core.Entites.Permission", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("permission_id");

                    b.Property<Guid>("ActionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("action_id");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("page_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("PermissionId")
                        .HasName("pk_permissions");

                    b.ToTable("permissions");
                });

            modelBuilder.Entity("eMotoCare.Core.Entites.Profile", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("profile_id");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("address_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<string>("ProfileCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("profile_code");

                    b.Property<int>("ProfileType")
                        .HasColumnType("int")
                        .HasColumnName("profile_type");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("ProfileId")
                        .HasName("pk_profiles");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("eMotoCare.Core.Entites.RMA", b =>
                {
                    b.Property<Guid>("RMAId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("rma_id");

                    b.Property<Guid>("ApprovedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("approved_by");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("profile_id");

                    b.Property<string>("RMACode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rma_code");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("vehicle_id");

                    b.HasKey("RMAId")
                        .HasName("pk_rm_as");

                    b.ToTable("rm_as");
                });

            modelBuilder.Entity("eMotoCare.Core.Entites.RMADetail", b =>
                {
                    b.Property<Guid>("RMADetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("rma_detail_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("Decision")
                        .HasColumnType("int")
                        .HasColumnName("decision");

                    b.Property<string>("InspectionResult")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("inspection_result");

                    b.Property<string>("IssueDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("issue_description");

                    b.Property<Guid>("RMAId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("rma_id");

                    b.Property<Guid>("ReferenceSource")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reference_source");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VehiclePartItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("vehicle_part_item_id");

                    b.HasKey("RMADetailId")
                        .HasName("pk_rma_details");

                    b.ToTable("rma_details");
                });

            modelBuilder.Entity("eMotoCare.Core.Entites.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("LastEditBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("last_edit_by");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role_code");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role_name");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("RoleId")
                        .HasName("pk_roles");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("eMotoCare.Core.Entites.RolePermission", b =>
                {
                    b.Property<Guid>("RolePermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_permission_id");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LastEditBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("last_edit_by");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("permission_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("RolePermissionId")
                        .HasName("pk_role_permissions");

                    b.ToTable("role_permissions");
                });

            modelBuilder.Entity("eMotoCare.Core.Entites.ServiceCenter", b =>
                {
                    b.Property<Guid>("ServiceCenterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("service_center_id");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("address_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<string>("ServiceCenterCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("service_center_code");

                    b.Property<string>("ServiceCenterName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("service_center_name");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("ServiceCenterId")
                        .HasName("pk_service_centers");

                    b.ToTable("service_centers");
                });

            modelBuilder.Entity("eMotoCare.Core.Entites.SlotTime", b =>
                {
                    b.Property<Guid>("SlotTimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("slot_time_id");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<Guid?>("LastEditBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("last_edit_by");

                    b.Property<Guid>("ServiceCenterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("service_center_id");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("SlotTimeId")
                        .HasName("pk_slot_times");

                    b.ToTable("slot_times");
                });

            modelBuilder.Entity("eMotoCare.Core.Entites.StaffProfile", b =>
                {
                    b.Property<Guid>("StaffProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("staff_profile_id");

                    b.Property<int>("Position")
                        .HasColumnType("int")
                        .HasColumnName("position");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("profile_id");

                    b.Property<Guid>("ServiceCenterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("service_center_id");

                    b.Property<string>("StaffCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("staff_code");

                    b.HasKey("StaffProfileId")
                        .HasName("pk_staff_profiles");

                    b.ToTable("staff_profiles");
                });

            modelBuilder.Entity("eMotoCare.Core.Entites.StageVehicle", b =>
                {
                    b.Property<Guid>("StageVehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("stage_vehicle_id");

                    b.Property<DateTime>("ActualExecutionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("actual_execution_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpectedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("expected_date");

                    b.Property<DateTime>("ExpectedEndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("expected_end_date");

                    b.Property<Guid>("MaintenaceStageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("maintenace_stage_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("vehicle_id");

                    b.Property<int>("VehicleStageStatus")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_stage_status");

                    b.HasKey("StageVehicleId")
                        .HasName("pk_stage_vehicles");

                    b.ToTable("stage_vehicles");
                });

            modelBuilder.Entity("eMotoCare.Core.Entites.Vehicle", b =>
                {
                    b.Property<Guid>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("vehicle_id");

                    b.Property<string>("ClassisNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("classis_number");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("EngineNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("engine_number");

                    b.Property<string>("LicensePlateNUmber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("license_plate_n_umber");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("profile_id");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("purchase_date");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VehicleModelId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("vehicle_model_id");

                    b.Property<DateTime>("WarrantyEndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("warranty_end_date");

                    b.Property<DateTime>("WarrantyStartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("warranty_start_date");

                    b.HasKey("VehicleId")
                        .HasName("pk_vehicles");

                    b.ToTable("vehicles");
                });

            modelBuilder.Entity("eMotoCare.Core.Entites.VehicleModel", b =>
                {
                    b.Property<Guid>("VehicleModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("vehicle_model_id");

                    b.Property<decimal>("BatteryCapacity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("battery_capacity");

                    b.Property<int?>("BatteryType")
                        .HasColumnType("int")
                        .HasColumnName("battery_type");

                    b.PrimitiveCollection<string>("Colors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("colors");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("FrontBrakes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("front_brakes");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("height");

                    b.Property<decimal>("Length")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("length");

                    b.Property<Guid>("MaintenancePlanId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("maintenance_plan_id");

                    b.Property<decimal>("MaximumPower")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("maximum_power");

                    b.Property<decimal>("MaximumSpeed")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("maximum_speed");

                    b.Property<string>("ModelCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("model_code");

                    b.Property<string>("ModelName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("model_name");

                    b.Property<int>("MotorType")
                        .HasColumnType("int")
                        .HasColumnName("motor_type");

                    b.Property<decimal>("RangePerCharge")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("range_per_charge");

                    b.Property<string>("RearBrakes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rear_brakes");

                    b.Property<string>("ShockAbsorbers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("shock_absorbers");

                    b.Property<decimal>("StandardChargingTime")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("standard_charging_time");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("WarrantyPeriod")
                        .HasColumnType("int")
                        .HasColumnName("warranty_period");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("weight");

                    b.Property<decimal>("Width")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("width");

                    b.HasKey("VehicleModelId")
                        .HasName("pk_vehicle_models");

                    b.ToTable("vehicle_models");
                });
#pragma warning restore 612, 618
        }
    }
}
